"""empty message

Revision ID: 2646b1acf732
Revises: 
Create Date: 2019-11-10 23:06:12.017652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2646b1acf732'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('migrate_version')
    op.create_unique_constraint('destination_tag_pk', 'dst__tag', ['destination_id', 'tag_id'])
    op.add_column('due_date', sa.Column('dst_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('student_goal_pk', 'due_date', ['student_id', 'goal_id'])
    op.create_foreign_key(None, 'due_date', 'destination', ['dst_id'], ['id'])
    op.create_unique_constraint('student_teacher_pk', 'role', ['student_id', 'teacher_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_teacher_pk', 'role', type_='unique')
    op.drop_constraint(None, 'due_date', type_='foreignkey')
    op.drop_constraint('student_goal_pk', 'due_date', type_='unique')
    op.drop_column('due_date', 'dst_id')
    op.drop_constraint('destination_tag_pk', 'dst__tag', type_='unique')
    op.create_table('migrate_version',
    sa.Column('repository_id', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('repository_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('version', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('repository_id', name='migrate_version_pkey')
    )
    # ### end Alembic commands ###
